ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.devopsdaws.online
CATALOGUE_HOST: catalogue-dev.devopsdaws.online
REDIS_HOST: redis-dev.devopsdaws.online
USER_HOST: user-dev.devopsdaws.online
CART_HOST: cart-dev.devopsdaws.online
MYSQL_HOST: mysql-dev.devopsdaws.online
SHIPPING_HOST: shipping-dev.devopsdaws.online
RABBITMQ_HOST: rabbitmq-dev.devopsdaws.online
PAYMENT_HOST: payment-dev.devopsdaws.online