- name: App setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Java setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yaml

- name: Systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

# This is used because import shipping data requires libraries like PyMySQL and crytopraphy is for password provided...
- name: Install Python dependencies # Pip is used to install, upgrade, or remove Python packages.
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography 
  - PyMySQL

- name: Import Shipping data # Database collection module is used to create, delete and  import/export MySQL dbs
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: "{{ SHIPPING_LOGIN_USER }}"
    login_password: "{{ SHIPPING_LOGIN_PASSWORD }}"
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: Start and Enable Shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
    enabled: yes