# $ANSIBLE_VAULT;1.1;AES256
# 37663931346331383833363064306564646333343963383364613235663563366234323339623561
# 6266343832633465356531633061326466653932346238370a643736373732656565613263373763
# 36363066363535613263616339323762386435383966666266653963633633666538623364643739
# 3665656631333434370a646266633731356632626264613134346637633061323530383031376264
# 39376339613837643135633362353439616231353436313431376538386337303637363335373965
# 3361303334633266353363373964356663643566363165323461 #1

MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/mysql_root_password', region='us-east-1', decrypt=True) }}"
#"{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/mysql_root_password', region='us-east-1', decrypt=True) }}"