- name: App setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python-setup.yaml

- name: Systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: Start and Enable Payment
  ansible.builtin.service:
    name: payment
    state: restarted
    enabled: yes