- name: Call common role
  # ansible.builtin.import_role: # 1
  ansible.builtin.include_role: # 2
    name: common
    tasks_from: include-vs-import.yaml
  when: os == "RedHat"
  loop: # 4
  - John
  - Joe