- name: Create system user roboshop
  ansible.builtin.user:
    name: roboshop
    system: true
    home: /app
    shell: /sbin/nologin
    comment: "Roboshop system user"

- name: Delete app directory # Befoe creating an app directory, we need to delete it if previously existed.
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Delete {{ component }} zip file # Before downloading, we need to delete it if existed.
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: Download the {{ component }}
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: Unarchive the {{ component }}  # Remote machine -> catalogue
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes # Provide yes if file already existed in the remote machine